#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <time.h>
typedef struct listItem {
    const char *word;
    const char *meaning;
} listItem;
enum chState {
	unKnown = 0,	// black
	notExist,		// gray
	right,			// green
	exist,			// yellow
};
#define wordCounts  (sizeof(wordlist) / sizeof(wordlist[0]))
#define red 	    "\033[1;31m"
#define green       "\033[1;32m"
#define yellow 	    "\033[1;93m"
#define gray 	    "\033[1;37m"
#define cend 	    "\033[0m"
#define ans(word, meaning, color)									\
	do {															\
		printf("The correct word is " color "%s" cend "\n", word);	\
		printf("The meaning is " color "%s" cend "\n", meaning);	\
	} while (0)
const char *suffix[10] = { "th", "st", "nd", "rd", "th", "th", "th", "th", "th", "th" };
listItem wordlist[] = {
    {"abnormal",			"adj. 不正常的"},
    {"absurd",				"adj. 荒缪的"},
    {"abundant",			"adj. 丰富的"},
    {"acute",				"adj. 敏锐的, 锋利的"},
    {"aggressive",			"adj. 侵略的, 好斗的"},
    {"ambiguous",			"adj. 模棱两可的, 模糊的"},
    {"ambitious",			"adj. 有雄心的, 有抱负的"},
    {"appropriate",			"adj. 合适的, 恰当的"},
    {"authentic",			"adj. 可靠的, 可信的"},
    {"average",				"adj. 一般的, 普通的"},
    {"barren",				"adj. 贫瘠的, 不毛的"},
    {"bound",				"adj. 一定的"},
    {"chronic",				"adj. 慢性的"},
    {"commentary",			"adj. 实况报道"},
    {"compact",				"adj. 紧凑的, 小巧的"},
    {"competitive",			"adj. 竞争性的, 具有竞争力的"},
    {"compact",				"adj. 紧凑的, 小巧的"},
    {"competitive",			"adj. 竞争性的, 具有竞争力的"},
    {"compulsory",			"adj. 强迫的, 强制的, 义务的"},
    {"confidential",		"adj. 机紧的, 秘密的"},
    {"conservative",		"adj. 保守的, 传统的"},
    {"consistent",			"adj. 和...一致"},
    {"conspicuous",			"adj. 显而易见的, 引人注目的"},
    {"crucial",				"adj. 关键的"},
    {"current",				"adj. 当前的"},
    {"decent",				"adj. 体面的, 像样的, 还不错的"},
    {"delicate",			"adj. 精细的, 微妙的, 精心处理的"},
    {"destructive",			"adj. 毁灭的"},
    {"economic",			"adj. 经济的"},
    {"elegant",				"adj. 优雅的, 优美的, 精致的"},
    {"embarrassing",		"adj. 令人尴尬的"},
    {"energetic",			"adj. 精力充沛的"},
    {"equivalent",			"adj. 相等的"},
    {"eternal",				"adj. 永恒的, 无休止的"},
    {"exclusive",			"adj. 独有的, 排他的"},
    {"extinct",				"adj. 灭绝的, 绝种的 "},
    {"fatal",				"adj. 致命的, 毁灭性的"},
    {"feasible",			"adj. 可行的"},
    {"feeble",				"adj. 脆弱的, 虚弱的"},
    {"rough",				"adj. 粗略的, 不精确的"},
    {"rude",				"adj. 粗鲁的, 不礼貌的"},
    {"sensitive",			"adj. 敏感的"},
    {"sheer",				"adj. 完全的, 十足的"},
    {"shrewd",				"adj. 精明的"},
    {"stationary",			"adj. 固定的"},
    {"subordinate",			"adj. 次要的, 从属的"},
    {"subtle",				"adj. 微妙的, 精巧的, 细微的"},
    {"superficial",			"adj. 肤浅的"},
    {"suspicious",			"adj. 对...怀疑"},
    {"gloomy",				"adj. 暗淡的"},
    {"greasy",				"adj. 油腻的"},
    {"identical",			"adj. 相同的, 一样的"},
    {"imaginative",			"adj. 富有想象力的, 爱想象的"},
    {"inaccessible",		"adj. 可接近的, 易使用的"},
    {"inadequate",			"adj. 不充分的, 不适当的"},
    {"incredible",			"adj. 难以置信的"},
    {"indignant",			"adj. 生气的, 愤怒的"},
    {"infectious",			"adj. 传染的, 传染性的"},
    {"inferior",			"adj. 较次的, 较劣的"},
    {"inferior",			"adj. 地位较低的, 较差的"},
    {"inherent",			"adj. 固有的, 生来的"},
    {"inspirational",		"adj. 灵感的"},
    {"intent",				"adj. 专心的, 专注的"},
    {"intricate",			"adj. 复杂精细的"},
    {"intrinsic",			"adj. 固有的, 本质的, 内在的"},
    {"irreplaceable",		"adj. 不能替换的, 不能代替的"},
    {"literal",				"adj. 文字的, 字面的, 逐字逐句的"},
    {"massive",				"adj. 大规模的, 大量的"},
    {"merciful",			"adj. 仁慈的, 宽大的"},
    {"mobile",				"adj. 活动的, 流动的"},
    {"naive",				"adj. 言行自然而天真的, 质朴的"},
    {"negligible",			"adj. 可忽略的, 微不足道的"},
    {"notorious",			"adj. 臭名昭著的, 声名狼藉的"},
    {"obedient",			"adj. 服从的, 顺从的"},
    {"obscure",				"adj. 模糊不清的"},
    {"optimistic",			"adj. 乐观的"},
    {"original",			"adj. 原先的, 最早的"},
    {"pathetic",			"adj. 悲哀的, 悲惨的"},
    {"persistent",			"adj. 坚持不懈的"},
    {"potential",			"adj. 可能的, 潜在的"},
    {"prevalent",			"adj. 普遍的, 流行的"},
    {"primitive",			"adj. 原始的, 早期的"},
    {"proficient",			"adj. 熟练的, 精通的"},
    {"profound",			"adj. 深刻的, 深远的"},
    {"prominent",			"adj. 突出的, 杰出的"},
    {"prompt",				"adj. 即刻的, 迅速的"},
    {"raw",				    "adj. 自然状态的, 未加工的"},
    {"relevant",			"adj. 与...有关的"},
    {"respectable",			"adj. 可尊敬的"},
    {"rewarding",			"adj. 值得的"},
    {"tedious",				"adj. 冗长的, 乏味的"},
    {"trivial",				"adj. 琐碎的, 不重要的"},
    {"turbulent",			"adj. 动荡的, 混乱的"},
    {"underlying",			"adj. 潜在的"},
    {"versatile",			"adj. 多才多艺的"},
    {"vivid",				"adj. 生动的, 栩栩如生的"},
    {"void",				"adj. 无效的"},
    {"vulnerable",			"adj. 易受伤的"},
    {"worth",				"adj. 值得"},    
    {"deliberately",		"adv. 故意, 有意地"},
    {"deliberately",		"adv. 深思熟虑地, 审慎地"},
    {"exclusively",			"adv. 仅仅地"},
    {"explicitly",			"adv. 明确地"},
    {"forcibly",			"adv. 强行地, 有力地"},
    {"formerly",			"adv. 原先地, 以前, 从前"},
    {"increasingly",		"adv. 日益, 越来越多地"},
    {"inevitably",			"adv. 必然地, 不可避免地"},
    {"intentionally",		"adv. 有意地, 故意地"},
    {"optimistically",		"adv. 乐观地"},
    {"outwardly",			"adv. 表面上, 外表上地"},
    {"presumably",			"adv. 大概, 可能, 据推测"},
    {"simultaneously",		"adv. 同时发生地"},
    {"somewhat",			"adv. 颇为, 稍稍, 有几分"},
    {"spontaneously",		"adv. 自发地, 自然产生地"},
    {"startlingly",			"adv. 惊人地"},
    {"triumphantly",		"adv. (欣喜)胜利地, 成功地"},
    {"unexpectedly",		"adv. 意外地"},
    {"virtually",		    "adv. 事实上, 实际地"},
    {"access",				"n. 入口, 通路, 接触"},
    {"accommodation",		"n. 住宿, 膳宿"},
    {"acknowledgement",		"n. 承认, 感谢, 致谢"},
    {"admiration",			"n. 欣赏"},
    {"advocate",			"n. 提倡者, 拥护者"},
    {"allowance",			"n. 津贴"},
    {"ambition",			"n. 野心, 雄心"},
    {"analogy",				"n. 相似, 模拟, 类比"},
    {"anticipation",		"n. 预期, 期望"},
    {"appreciation",		"n. 感谢, 感激"},
    {"array",				"n. 陈列, 一系列"},
    {"assurance",			"n. 保证"},
    {"blame",				"n. 责任"},
    {"blunder",				"n. 错误, 大错"},
    {"budget",				"n. 预算"},
    {"capability",			"n. 能力, 才能"},
    {"cash",				"n. 现金"},
    {"expenditure",			"n. 开支"},
    {"extinction",			"n. 灭绝"},
    {"fashion",				"n. 方式, 样子"},
    {"flaw",				"n. 裂纹, 瑕疵"},
    {"fortune",				"n. 财产, 大笔的钱"},
    {"fraction",			"n. 小部分, 一点"},
    {"fuse",				"n. 保险丝"},
    {"guarantee",			"n. 保修单"},
    {"guilt",				"n. 犯罪"},
    {"harmony",			    "n. 与...协调一致, 和谐"},
    {"hospitality",			"n. 友好款待, 好客"},
    {"humor",				"n. 情绪, 心境"},
    {"indifference",		"n. 不关心, 冷漠"},
    {"illusion",			"n. 错觉, 假象"},
    {"ingredient",			"n. 成分"},
    {"insight",				"n. 理解, 洞察力"},
    {"inspection",			"n. 检查, 视察"},
    {"instinct",			"n. 本能, 直觉"},
    {"integrity",			"n. 正直, 诚实"},
    {"intuition",			"n. 直觉"},
    {"lease",				"n. 租约, 契约"},
    {"legislation",			"n. 立法, 法律"},
    {"limitation",			"n. 局限性, 缺点"},
    {"loyalty",				"n. 忠诚, 忠心"},
    {"luxury",				"n. 奢侈, 豪华"},
    {"manifestation",		"n. 表现(形式)"},
    {"mechanism",			"n. 机械装置"},
    {"minority",			"n. 少数"},
    {"misfortune",			"n. 不幸, 灾难"},
    {"morality",			"n. 道德, 美德"},
    {"notion",				"n. 概念, 观念, 理解"},
    {"obligation",			"n. (法律上或道义上的)责任"},
    {"occasion",			"n. 场合"},
    {"opponent",			"n. 敌人, 对手"},
    {"ornament",			"n. 装饰, 装饰品"},
    {"participation",		"n. 参加, 加入"},
    {"pastime",				"n. 消遣, 娱乐"},
    {"pattern",				"n. 模式"},
    {"penalty",				"n. 制裁, 惩罚"},
    {"pension",				"n. 养老金"},
    {"personality",			"n. 人格, 人性"},
    {"circulation",			"n. (书报等的)发行量"},
    {"commitment",			"n. 承诺, 许诺"},
    {"compensation",		"n. 补偿, 赔偿"},
    {"consideration",		"n. 考虑"},
    {"constitution",		"n. 组成, 构成"},
    {"consultant",			"n. 顾问"},
    {"controversy",			"n. 争论, 辩论"},
    {"damage",				"n. 损坏"},
    {"debate",				"n. 争论, 辩论"},
    {"denial",				"n. 否认, 否定, 拒绝给与(正义, 权利)"},
    {"digest",				"n. 摘要, 简编"},
    {"dilemma",				"n. 窘境, 困境"},
    {"distinction",			"n. 区分, 辨别"},
    {"emergency",			"n. 紧急情况"},
    {"encouragement",		"n. 鼓励"},
    {"essence",				"n. 本质"},
    {"estimate",			"n. 估计"},
    {"pledge",				"n. 保证, 誓言"},
    {"position",			"n. 位置, 职位, 职务"},
    {"predecessor",			"n. 前任, 原有的事物"},
    {"premise",				"n. 前提, 假设"},
    {"prescription",		"n. 处方"},
    {"preservation",		"n. 保护, 防护"},
    {"prestige",			"n. 威信, 威望"},
    {"priority",			"n. 优先(权)"},
    {"prospect",			"n. 前景, 可能性"},
    {"rate",				"n. 速度"},
    {"ration",				"n. 比率"},
    {"recession",			"n. (经济)衰退, 不景气；撤退, 退出"},
    {"reflection",			"n. 反映, 表现"},
    {"reputation",			"n. 名声, 声望"},
    {"reservation",			"n. 贮存, 贮藏"},
    {"reservation",			"n. 预订"},
    {"revenue",				"n. 税收, 岁入"},
    {"rival",				"n. 竞争对手"},
    {"routine",				"n. 常规, 惯例, 例行公事"},
	{"ruler",				"n. 尺子, 统治者"},
    {"scene",				"n. 景色, 景象"},
    {"scorn",				"n. 轻蔑, 鄙视"},
    {"shortage",			"n. 短缺, 不足"},
    {"smash",				"n. 打碎, 粉碎"},
    {"stability",			"n. 稳定(性), 稳固"},
    {"stack",				"n. 堆, 一堆"},
    {"standard",			"n. 标准"},
    {"surface",				"n. 表面"},
    {"temperament",			"n. 气质, 性格"},
    {"threshold",			"n. 开端, 入口"},
    {"tolerance",			"n. 容忍, 忍耐力"},
    {"transaction",			"n. 处理, 办理, 交易"},
    {"transition",			"n. 过渡, 转变"},
    {"trend",				"n. 倾向, 趋势"},
    {"variation",			"n. 变化, 变动"},
    {"warehouse",			"n. 货仓"},
    {"way",				    "n. 方式 "},
    {"abandon",				"v. 抛弃, 放弃"},
    {"acknowledge",			"v. 对...表示谢忱, 报偿"},
    {"acquaint",			"v. 熟悉, 认识"},
    {"acquire",				"v. (靠自己的能力、努力或行为)获得, 得到"},
    {"afford",				"v. 付得起"},
    {"allege",				"v. 断言, 宣称"},
    {"alternate",			"v. 交替, 轮流"},
    {"anticipate",			"v. 预期"},
    {"applaud",				"v. 赞扬, 称赞"},
    {"ascend",				"v. 上升, 攀登"},
    {"ascribe",				"v. 归因于, 归功于"},
    {"assemble",			"v. 集合, 聚集"},
    {"assign",				"v. 分派, 指派(职务, 任务)"},
    {"attribute",			"v. 归因于"},
    {"base",				"v. 建立在...的基础上"},
    {"bewilder",			"v. 迷惑, 弄糊涂"},
    {"breed",				"v. 培育, 养育"},
    {"cling",				"v. 坚守, 抱紧"},
    {"coincide",			"v. 相同, 相一致"},
    {"collaborate",			"v. 合著, 合作"},
    {"collide",				"v. 互撞, 碰撞"},
    {"commence",			"v. 开始"},
    {"compensate",			"v. 补偿, 赔偿"},
    {"complement",			"v. 与...结合, 补充"},
    {"comply",				"v. 遵守"},
    {"conceive",			"v. 想出, 设想"},
    {"concern",				"v. 涉及"},
    {"condense",			"v. 压缩, 浓缩"},
    {"conflict",			"v. 冲突, 战争"},
    {"conform",				"v. 符合, 遵守, 适应"},
    {"confront",			"v. 面对, 面临"},
    {"conserve",			"v. 保护, 保存"},
    {"consolidate",			"v. 巩固"},
    {"convey",				"v. 表达, 传达"},
    {"crash",				"v. (飞机)坠毁"},
    {"cruise",				"v. 航行, 漫游"},
    {"dazzle",				"v. 使眩目, 耀眼"},
    {"deceive",				"v. 欺骗, 哄骗"},
    {"decline",				"v. 下降, 减少"},
    {"dedicate",			"v. 奉献, 献身, 致力于"},
    {"defend",				"v. 为...辩护"},
    {"magnify",				"v. 放大"},
    {"mean",				"v. 打算, 意欲"},
    {"mingle",				"v. 混合起来, 相混合"},
    {"minimize",			"v. 对...做最低估计"},
    {"monitor",				"v. 检测, 监测"},
    {"neglect",				"v. 忽视"},
    {"occupy",				"v. 占领, 使忙碌"},
    {"oppress",				"v. 压迫"},
    {"originate",			"v. 首创, 起源"},
    {"overlap",				"v. 部分重叠"},
    {"overwhelm",			"v. 压倒, 浸没, 使不安"},
    {"parade",				"v. 游行"},
    {"permeate",			"v. 渗入, 渗透"},
    {"prescribe",			"v. 处方, 开药"},
    {"preside",				"v. 主持"},
    {"prolong",				"v. 延长, 拖延"},
    {"promise",				"v. 许诺"},
    {"propel",				"v. 推进, 推动"},
    {"protest",				"v. 抗议, 反对"},
    {"provoke",				"v. 引起, 激起"},
    {"radiate",				"v. 辐射状发出, 从中心向各方伸展出"},
    {"reconcile",			"v. 使和好, 调解"},
    {"refresh",				"v. 提神, 使清新"},
    {"refute",				"v. 证明...不对(是错误的), 驳诉"},
    {"remain",				"v. 停留, 依旧是"},
    {"repel",				"v. 抗御, 抵拒"},
    {"defy",				"v. 违抗, 藐视"},
    {"deny",				"v. 否认"},
    {"deprive",				"v. 剥夺"},
    {"derive",				"v. 得来, 得到"},
    {"descend",				"v. 下落"},
    {"descend",				"v. 下来, 下去"},
    {"deserve",				"v. 值得"},
    {"deviate",				"v. (使)背离, (使)偏离"},
    {"disguise",			"v. 假扮, 伪装"},
    {"dominate",			"v. 统治, 占据"},
    {"drain",				"v. 渐渐耗尽"},
    {"duplicate",			"v. 复制, 重复"},
    {"eliminate",			"v. 消除"},
    {"endure",				"v. 忍受, 忍耐"},
    {"enhance",				"v. 提高, 增加"},
    {"enhance",				"v. 提高"},
    {"enroll",				"v. 使成为...的成员, 注册"},
    {"evoke",				"v. 引起, 唤起"},
    {"exclaim",				"v. 呼喊, 欢呼"},
    {"expire",				"v. 到期, 期满"},
    {"explore",				"v. 探险, 探索"},
    {"defy",				"v. 违抗, 藐视"},
    {"deny",				"v. 否认"},
    {"deprive",				"v. 剥夺"},
    {"derive",				"v. 得来, 得到"},
    {"descend",				"v. 下落"},
    {"descend",				"v. 下来, 下去"},
    {"deserve",				"v. 值得"},
    {"deviate",				"v. (使)背离, (使)偏离"},
    {"disguise",			"v. 假扮, 伪装"},
    {"dominate",			"v. 统治, 占据"},
    {"drain",				"v. 渐渐耗尽"},
    {"duplicate",			"v. 复制, 重复"},
    {"eliminate",			"v. 消除"},
    {"endure",				"v. 忍受, 忍耐"},
    {"enhance",				"v. 提高, 增加"},
    {"enhance",				"v. 提高"},
    {"enroll",				"v. 使成为...的成员, 注册"},
    {"evoke",				"v. 引起, 唤起"},
    {"exclaim",				"v. 呼喊, 欢呼"},
    {"expire",				"v. 到期, 期满"},
    {"explore",				"v. 探险, 探索"},
    {"flap",				"v. (鸟)振翅(飞行)"},
    {"follow",				"v. 遵从"},
    {"furnish",				"v. 配备, 装饰"},
    {"gaze",				"v. 凝视, 注视"},
    {"gear",				"v. 使适应, 使适合"},
    {"grieve",				"v. 使伤心, 使悲伤"},
    {"hamper",				"v. 妨碍, 限制"},
    {"haul",				"v. 拖, 拉"},
    {"hinder",				"v. 阻碍, 妨害"},
    {"hoist",				"v. 举起, 升起, 吊起"},
    {"identify",			"v. 认出, 确认"},
    {"ignite",				"v. 引燃"},
    {"immerse",				"v. 使浸没"},
    {"impose",				"v. 把...强加于"},
    {"induce",				"v. 劝诱, 诱导"},
    {"indulge",				"v. 纵容, 放任"},
    {"intend",				"v. 意欲"},
    {"interpret",			"v. 解释, 说明"},
    {"jeopardize",			"v. 危及, 损坏"},
    {"linger",				"v. 逗留, 徘徊, 留恋；迟缓, 拖延"},
    {"locate",				"v. 位于"},
    {"rescue",				"v. 营救, 救援"},
    {"resign",				"v. 辞职"},
    {"resort",				"v. 求助, 凭借, 诉诸"},
    {"resume",				"v. 重新开始, 继续"},
    {"revenge",				"v. 报仇, 报复"},
    {"tackle",				"v. 解决, 处理"},
    {"tempt",				"v. 引诱, 劝诱"},
    {"tempt",				"v. 引诱, 劝诱"},
    {"terminate",			"v. 终止, 结束"},
    {"transmit",			"v. 传播, 传递"},
    {"verify",				"v. 证实, 证明"},
    {"view",				"v. 视为, 看做"},
    {"wreck",				"v. (船只)失事"},
};
